steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/louielabs-website', 
      '-f', 'html-website/Dockerfile', 
      'html-website'
    ]
images:
  - 'gcr.io/$PROJECT_ID/louielabs-website'
